name: Hello World App CI with Rollback

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # --------- Stage 1: Checkout ---------
      - name: Checkout Code
        uses: actions/checkout@v3

      # --------- Stage 2: Build ---------
      - name: Build Stage
        run: |
          echo "🔧 Building Hello World App..."
          # Simulate build (e.g., javac HelloWorld.java or npm install)
          echo "Build success."

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # --------- Stage 3: Test ---------
      - name: Test Stage
        run: |
          echo "Running tests..."
          # Simulate a test (e.g., python test_hello.py or npm test)
          echo "Tests passed."

      # --------- Stage 4: Deploy ---------
      - name: Deploy Stage
        run: |
          echo "🚀 Deploying Hello World App..."
          # Simulate deployment (e.g., start a server or upload to a cloud)
          echo "Hello, World!"
          # Simulate success/failure
          exit 1  # Uncomment to simulate failure

      # --------- Stage 5: Rollback ---------
      - name: Rollback if Failed
        if: failure()
        run: |
          echo "Something failed. Rolling back the last change..."
          git revert HEAD --no-edit || echo "Rollback skipped (maybe nothing to revert)."
